/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GET_FILE_H_RPCGEN
#define _GET_FILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct get_file_content_1_argument {
	char *arg1;
	int arg2;
};
typedef struct get_file_content_1_argument get_file_content_1_argument;

#define GETFILEPROG 0x2000000
#define GETFILE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_FILE_CONTENT 1
extern  char ** get_file_content_1(char *, int , CLIENT *);
extern  char ** get_file_content_1_svc(char *, int , struct svc_req *);
#define GET_FILE_TRANS 2
extern  int * get_file_trans_1(char *, CLIENT *);
extern  int * get_file_trans_1_svc(char *, struct svc_req *);
extern int getfileprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_FILE_CONTENT 1
extern  char ** get_file_content_1();
extern  char ** get_file_content_1_svc();
#define GET_FILE_TRANS 2
extern  int * get_file_trans_1();
extern  int * get_file_trans_1_svc();
extern int getfileprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_get_file_content_1_argument (XDR *, get_file_content_1_argument*);

#else /* K&R C */
extern bool_t xdr_get_file_content_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GET_FILE_H_RPCGEN */
