/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "get_file.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static char **
_get_file_content_1 (get_file_content_1_argument *argp, struct svc_req *rqstp)
{
	return (get_file_content_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_get_file_trans_1 (char * *argp, struct svc_req *rqstp)
{
	return (get_file_trans_1_svc(*argp, rqstp));
}

static void
getfileprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		get_file_content_1_argument get_file_content_1_arg;
		char *get_file_trans_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case GET_FILE_CONTENT:
		_xdr_argument = (xdrproc_t) xdr_get_file_content_1_argument;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) _get_file_content_1;
		break;

	case GET_FILE_TRANS:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _get_file_trans_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (GETFILEPROG, GETFILE_VER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, GETFILEPROG, GETFILE_VER, getfileprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (GETFILEPROG, GETFILE_VER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, GETFILEPROG, GETFILE_VER, getfileprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (GETFILEPROG, GETFILE_VER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
