/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _GET_FILE_H_RPCGEN
#define _GET_FILE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define GETFILEPROG 0x2fffffff
#define GETFILE_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_FILE_CONTENT 1
extern  char ** get_file_content_1(char *, CLIENT *);
extern  char ** get_file_content_1_svc(char *, struct svc_req *);
extern int getfileprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_FILE_CONTENT 1
extern  char ** get_file_content_1();
extern  char ** get_file_content_1_svc();
extern int getfileprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_GET_FILE_H_RPCGEN */
